# Generated by Django 5.0.4 on 2024-04-19 07:43

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='address',
            field=models.TextField(default='jane street, New York'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='city',
            field=models.TextField(default='New York'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2024, 4, 19, 7, 43, 26, 287247, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='trainer',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='trainer',
            name='experience',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=2),
        ),
        migrations.AddField(
            model_name='trainer',
            name='gender',
            field=models.TextField(default='male'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='jod',
            field=models.DateField(default=datetime.datetime(2024, 4, 19, 7, 43, 26, 287278, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='trainer',
            name='name',
            field=models.TextField(default='Lucifer'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='trainspec',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='phone',
            field=models.CharField(default=0, max_length=13),
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='anonymous')),
                ('age', models.IntegerField(default=10)),
                ('sex', models.CharField(choices=[('m', 'male'), ('f', 'female'), ('o', 'other')], default='m', max_length=1)),
                ('height', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('weight', models.DecimalField(decimal_places=2, default=50, max_digits=3)),
                ('address', models.TextField(default='Jane street, New York')),
                ('subscription', models.CharField(choices=[('M', 'monthly'), ('Q', 'Quarterly'), ('A', 'Annualy')], default='M', max_length=10)),
                ('fees', models.CharField(choices=[('P', 'paid'), ('NP', 'Not_paid')], max_length=10)),
                ('trainer', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gym_management.trainer')),
            ],
        ),
    ]
