# Generated by Django 5.0.4 on 2024-05-03 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_management', '0002_trainer_address_trainer_city_trainer_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2024, 5, 3, 8, 59, 53, 716210, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='jod',
            field=models.DateField(default=datetime.datetime(2024, 5, 3, 8, 59, 53, 716210, tzinfo=datetime.timezone.utc)),
        ),
    ]
