# Generated by Django 5.0.4 on 2024-05-03 09:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_management', '0003_alter_trainer_date_of_birth_alter_trainer_jod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2024, 5, 3, 9, 3, 7, 68746, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='jod',
            field=models.DateField(default=datetime.datetime(2024, 5, 3, 9, 3, 7, 68746, tzinfo=datetime.timezone.utc)),
        ),
    ]
