# Generated by Django 5.0.6 on 2024-07-09 05:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "gym_management",
            "0006_alter_member_fees_alter_trainer_date_of_birth_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="height",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name="member",
            name="weight",
            field=models.DecimalField(decimal_places=2, default=50, max_digits=4),
        ),
        migrations.AlterField(
            model_name="trainer",
            name="date_of_birth",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 7, 9, 5, 53, 49, 274936, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="trainer",
            name="jod",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 7, 9, 5, 53, 49, 274960, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
