# Generated by Django 5.0.6 on 2024-07-13 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gym_management", "0007_alter_member_height_alter_member_weight_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainer",
            name="date_of_birth",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 7, 13, 17, 35, 5, 563751, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="trainer",
            name="jod",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 7, 13, 17, 35, 5, 563808, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
