# Generated by Django 5.0.6 on 2024-07-13 17:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gym_management", "0008_alter_trainer_date_of_birth_alter_trainer_jod"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainer",
            name="date_of_birth",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="trainer",
            name="jod",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
