# Generated by Django 5.0.6 on 2024-07-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gym_management", "0009_alter_trainer_date_of_birth_alter_trainer_jod"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainer",
            name="experience",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
